services:
  db:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  rabbitmq:
    image: rabbitmq:3.13.6-management
    hostname: rabbitmq
    env_file:
      - .env
    ports:
      - 15672:15672
      - 5672:5672
    # volumes:
    #   - /var/lib/rabbitmq
    restart: always
volumes:
  pgdata:
